spring.application.name=rest-demo
server.port=8081
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=REST API Demo
info.app.version=1.0.0
info.app.description=A simple REST API demo application
#spring.profiles.active=dev

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rest_demo_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=hihihi123

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG