create table task(
task_id int generated by default as identity primary key,
description varchar(100) not null
)

insert into task(description) values('Eat');
insert into task(description) values('Sleep');

select nextval('task_task_id_seq');

insert into task(task_id, description) values(3, 'Repeat')